name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4 
        with:
          node-version: '18.x'
      
      - name: Update .env file
        run: |
          $envFile = ".env"
          if (!(Test-Path $envFile)) {
            Write-Host ".env file does not exist. Creating a new one."
            New-Item -Path $envFile -ItemType File -Force
          }
          Write-Host "Updating .env file with new values."
          $envContent = Get-Content -Path $envFile -Raw
          $updates = @{
            "MYSQL_USER"     = "${{ secrets.MYSQL_USER }}"
            "MYSQL_DATABASE" = "${{ secrets.MYSQL_DATABASE }}"
            "MYSQL_PASSWORD" = "${{ secrets.MYSQL_PASSWORD }}"
            "MYSQL_HOST"     = "${{ secrets.MYSQL_HOST }}"
            "MYSQL_PORT"     = "${{ secrets.MYSQL_PORT }}"
          }
          foreach ($key in $updates.Keys) {
            if ($envContent -match "^$key=.*$") {
              $envContent = $envContent -replace "^$key=.*$", "$key=$($updates[$key])"
            } else {
              $envContent += "`n$key=$($updates[$key])"
            }
          }
          Set-Content -Path $envFile -Value $envContent
        shell: powershell

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm start
