name: start

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    env:
      FusionLiteServerHost: ${{ vars.FUSIONLITE_SERVER_HOST }}
      FusionLiteServerPort: ${{ vars.FUSIONLITE_SERVER_PORT }}
      FusionLiteServerUser: ${{ secrets.FUSIONLITE_SERVER_USER }}
      FusionLiteServerKeyFile: ${{ secrets.FUSIONLITE_SERVER_KEY_FILE }}
      FusionLiteProject: ${{ github.event.repository.name }}
      ApplicationFile: ${{ github.event.repository.name }}.zip
      ApplicationInclude: ""
      ApplicationExclude: ""
      InstrumentedFolder: Instrumented
      InstrumentedFile: ${{ github.event.repository.name }}.zip

    steps:
      - name: Print Environment Variable and Unzip File
        run: |
          Write-Output "The value of FusionLiteProject is: $env:FusionLiteProject"
          
          # Define paths for the zip file and extraction destination
          $zipFile = "$env:FusionLiteProject/Output/$($env:FusionLiteProject).zip"
          $destination = "$env:FusionLiteProject/Output/unzipped"

          # Ensure the destination directory exists
          if (-not (Test-Path -Path $destination)) {
              New-Item -ItemType Directory -Path $destination
          }

          # Unzip the file
          Expand-Archive -Path $zipFile -DestinationPath $destination
