name: start

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: ${{ github.workspace }}

    env:
      FusionLiteServerHost: ${{ vars.FUSIONLITE_SERVER_HOST }}
      FusionLiteServerPort: ${{ vars.FUSIONLITE_SERVER_PORT }}
      FusionLiteServerUser: ${{ secrets.FUSIONLITE_SERVER_USER }}
      FusionLiteServerKeyFile: ${{ secrets.FUSIONLITE_SERVER_KEY_FILE }}
      FusionLiteProject: ${{ github.event.repository.name }}
      ApplicationFile: ${{ github.event.repository.name }}.zip
      ApplicationInclude: ""
      ApplicationExclude: ""
      InstrumentedFolder: Instrumented
      InstrumentedFile: ${{ github.event.repository.name }}.zip

    steps:
      - name: Create Folder
        run: |
          if not exist "Instrumented-Application" mkdir Instrumented-Application

      - name: Instrumented File Unzip
        run: |
          # Using unzip command to extract the file and overwrite
          unzip -o "$env:InstrumentedFolder\$env:InstrumentedFile" -d "$env:InstrumentedFolder/Instrumented-Application" > $null 2>&1

      - name: Start Application
        run: |
          set NODE_PATH=. && start /B npm start
          
      # Uncomment if you want to remove the Instrumented Zip
      # - name: Remove Instrumented Zip
      #   run: |
      #     Remove-Item -Path "$env:InstrumentedFolder\$env:InstrumentedFile" -Force
