name: start

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Print Environment Variable
        run: |
          Write-Output "The value of FusionLiteProject/Output is: $env:FusionLiteProject"
