name: start

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    env:
      FusionLiteServerHost: ${{ vars.FUSIONLITE_SERVER_HOST }}
      FusionLiteServerPort: ${{ vars.FUSIONLITE_SERVER_PORT }}
      FusionLiteServerUser: ${{ secrets.FUSIONLITE_SERVER_USER }}
      FusionLiteServerKeyFile: ${{ secrets.FUSIONLITE_SERVER_KEY_FILE }}
      FusionLiteProject: ${{ github.event.repository.name }}
      ApplicationFile: ${{ github.event.repository.name }}.zip
      ApplicationInclude: ""
      ApplicationExclude: ""
      InstrumentedFolder: Instrumented
      InstrumentedFile: ${{ github.event.repository.name }}.zip

    steps:
      - name: Print Environment Variable and Unzip File
        run: |
          Write-Output "The value of FusionLiteProject is: $env:FusionLiteProject"
      
      - name: Listing Available Files in Output Folder
        run: |
          # Create the SFTP command to list files in the output folder
          echo "cd $env:FusionLiteProject/Output`nls`nexit" | Out-File -FilePath "sftp_list.txt" -Encoding ASCII

          # Run the SFTP command to list files
          sftp -b sftp_list.txt -i $env:FusionLiteServerKeyFile -P $env:FusionLiteServerPort $env:FusionLiteServerUser@$env:FusionLiteServerHost
